name: Activity Filters
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - 'dev*'
      - main
jobs:
  demo-example:
    runs-on: ubuntu-latest

    steps:
      - name: example step
        run: echo "Example Run"

