name: Artifact Downloads
on: push


jobs:
  demo-example:
    runs-on: ubuntu-latest

    steps:
      - name: Make the File
        run: |
          touch my_file_to_download
          echo "Hi" >> my_file_to_download
          echo "Hibbah" >> my_file_to_download
      - name: Download File to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my_file_to_download
          path: /home/runner/work/github_actions_demo/github_actions_demo/my_file_to_download