name: Artifact Downloads
on: push


jobs:
  demo-example:
    runs-on: ubuntu-latest

    steps:
      - name: Make the File
        run: |
          touch my_file_to_download
          echo "Hi" >> my_file_to_download
          echo "Hibbah" >> my_file_to_download
      - name: Download File to Artifacts
        run: |
          pwd
          ls -l