name: GitHub Custom Actions
on: workflow_dispatch

jobs:
  on-push-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Step
        run: git clone https://github.com/Hibrar/webdev_website.git
#        uses: actions/checkout@v4
      - name: Install Tree
        run: sudo apt install tree -y
      - name: Investigate Repo
        run: |
          pwd
          tree